# Generated by Django 5.1.4 on 2025-01-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=255)),
                ('house_no', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('DE', 'Germany'), ('AT', 'Austria'), ('CH', 'Switzerland'), ('DK', 'Denmark'), ('SE', 'Sweden'), ('NO', 'Norway'), ('FI', 'Finland'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('LU', 'Luxembourg'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('SK', 'Slovakia'), ('HU', 'Hungary'), ('SI', 'Slovenia'), ('HR', 'Croatia'), ('RS', 'Serbia'), ('BA', 'Bosnia and Herzegovina'), ('ME', 'Montenegro'), ('AL', 'Albania'), ('MK', 'North Macedonia'), ('BG', 'Bulgaria'), ('RO', 'Romania'), ('GR', 'Greece'), ('TR', 'Turkey'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy')], max_length=2)),
                ('special_conditions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
