# Generated by Django 5.1.4 on 2025-01-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_internet_operator_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='segment',
            field=models.IntegerField(choices=[(11, 'Kat. und feste Grp.'), (12, 'Nur feste Grp., mit ZV'), (13, 'Nur Amtg., Linie, Schü.'), (14, 'Achtung: Paketer'), (2, 'Vbd., Gem., Kirche'), (3, 'Prvt., Club, Verein'), (41, 'GW, KK, Partei'), (42, 'Firma, Business'), (51, 'Bus-Fili., RB, Agentur'), (52, 'Indi-Veranstalter'), (6, 'Zeitung, Medien'), (7, 'IFA-Gruppe'), (8, 'Wettbewerb'), (9, 'D: check. Ausl: gecheckt'), (10, 'VA, keine weitere Info')], default=7),
        ),
    ]
