# Generated by Django 5.1.4 on 2025-02-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('operators', '0004_hotel_operatorinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='double_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='operators.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='segment',
            field=models.IntegerField(choices=[(11, 'Kat. und feste Grp.'), (12, 'Nur feste Grp., mit ZV'), (13, 'Nur Amtg., Linie, Schü.'), (14, 'Achtung: Paketer'), (2, 'Vbd., Gem., Kirche'), (3, 'Prvt., Club, Verein'), (41, 'GW, KK, Partei'), (42, 'Firma, Business'), (51, 'Bus-Fili., RB, Agentur'), (52, 'Indi-Veranstalter'), (6, 'Zeitung, Medien'), (7, 'IFA-Gruppe'), (8, 'Wettbewerb'), (9, 'D: check. Ausl: gecheckt'), (10, 'VA, keine weitere Info')], default=7),
        ),
        migrations.AddField(
            model_name='booking',
            name='single_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
