# Generated by Django 5.1.4 on 2025-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('follow_up', 'Follow-up')], default='pending', max_length=20)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
