# Generated by Django 5.1.4 on 2025-02-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_operator_bundesland_operator_sales_rep'),
        ('sales', '0003_salesactivity_sales_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the season, e.g., Summer, Winter, etc.', max_length=50)),
                ('start_date', models.DateField(help_text='The start date of the season.')),
                ('end_date', models.DateField(help_text='The end date of the season.')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='operators.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HotelSeasonPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(help_text='Room type, e.g., Single, Double, Suite, etc.', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the room during the season.', max_digits=10)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, help_text='Weekend price for the room.', max_digits=10, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='sales.hotelseason')),
            ],
            options={
                'unique_together': {('season', 'room_type')},
            },
        ),
    ]
